CREATE TABLE `type_018_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `counttype` int(10) NOT NULL DEFAULT '0' COMMENT '统计类型',
  `param` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '根据不同统计类型，需要记录的数据',
  `consume_money` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的金钱数量',
  `consume_emoney` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的钻石数量',
  `consume_tired` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的钻石数量',
  `consume_currency_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型1的数量',
  `consume_currency_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型2的数量',
  `consume_currency_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型3的数量',
  `consume_currency_4` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型4的数量',
  `consume_currency_5` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型5的数量',
  `consume_currency_6` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型6的数量',
  `consume_currency_7` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型7的数量',
  `consume_currency_8` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型8的数量',
  `consume_currency_9` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型9的数量',
  `consume_currency_10` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗货币类型1的数量',
  `consume_item_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_4` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_4` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_5` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_5` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_6` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_6` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_7` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_7` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_8` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_8` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_9` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_9` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `consume_item_10` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具或者精灵ID',
  `consume_num_10` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '消耗的道具和精灵的数量',
  `get_money` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的金钱数量',
  `get_emoney` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的钻石数量',
  `get_tired` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的钻石数量',
  `get_currency_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型1的数量',
  `get_currency_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型2的数量',
  `get_currency_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型3的数量',
  `get_currency_4` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型4的数量',
  `get_currency_5` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型5的数量',
  `get_currency_6` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型6的数量',
  `get_currency_7` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型7的数量',
  `get_currency_8` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型8的数量',
  `get_currency_9` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型9的数量',
  `get_currency_10` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得货币类型1的数量',
  `get_item_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_4` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_4` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_5` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_5` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_6` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_6` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_7` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_7` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_8` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_8` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_9` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_9` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  `get_item_10` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具或者精灵ID',
  `get_num_10` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '获得的道具和精灵的数量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2399 DEFAULT CHARSET=utf8;


CREATE TABLE `type_015_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `task_id` int(10) unsigned NOT NULL COMMENT '任务id',
  `add_activity` int(10) NOT NULL COMMENT '增加的活跃度',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

CREATE TABLE `type_014_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `awards_type` varchar(64) NOT NULL COMMENT '奖励类型，多个中间用#隔开',
  `awards_id` varchar(64) NOT NULL COMMENT '奖励id，多个中间用#隔开',
  `awards_num` varchar(64) NOT NULL COMMENT '奖励数量，多个中间用#隔开',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;

CREATE TABLE `type_013_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `select_fairy_id` int(10) unsigned NOT NULL COMMENT '新手选择的精灵id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;


CREATE TABLE `type_012_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `buy_type` tinyint(2) NOT NULL COMMENT '1：联盟大赛',
  `buy_num` int(10) NOT NULL COMMENT '购买获得的次数',
  `currency_type` tinyint(2) NOT NULL COMMENT '消耗的货币类型',
  `currency_num` int(10) NOT NULL COMMENT '消耗的货币数量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `type_011_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `battle_type` tinyint(1) NOT NULL COMMENT '1：全球对战，2：联盟对战',
  `result` tinyint(1) NOT NULL COMMENT '0：失败，1胜利',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


CREATE TABLE `type_010_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `shop_type` tinyint(2) NOT NULL COMMENT '商店类型',
  `shop_name` varchar(32) NOT NULL COMMENT '商店名称',
  `currency_type` tinyint(2) NOT NULL COMMENT '消耗的货币类型',
  `currency_num` int(10) NOT NULL COMMENT '消耗货币数量',
  `currency_name` varchar(32) NOT NULL COMMENT '消耗的货币名称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;


CREATE TABLE `type_009_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `user_fighting_capacity` int(10) NOT NULL COMMENT '玩家战斗力',
  `instance_id` int(10) unsigned NOT NULL COMMENT '关卡id',
  `instance_type` tinyint(2) NOT NULL COMMENT '1：普通副本，2：精英副本，3：精英挑战',
  `result` tinyint(1) NOT NULL COMMENT '0：通关失败，1：通关成功',
  `fairys_id` varchar(64) NOT NULL COMMENT '上阵精灵id，中间用#隔开，未上阵的用‘-’',
  `fairys_level` varchar(64) NOT NULL COMMENT '上阵精灵等级，中间用#隔开，未上阵的用‘-’',
  `fairys_fighting_capacity` varchar(64) NOT NULL COMMENT '上阵精灵战斗力，中间用#隔开，未上阵的用‘-’',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=278 DEFAULT CHARSET=utf8;


CREATE TABLE `type_008_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `exchange_type` tinyint(1) NOT NULL COMMENT '0：初级交换，1：中级交换，2：高级交换',
  `use_fairy_1` int(10) unsigned NOT NULL COMMENT '消耗的精灵1',
  `use_fairy_2` int(10) unsigned NOT NULL COMMENT '消耗的精灵2',
  `use_fairy_3` int(10) unsigned NOT NULL COMMENT '消耗的精灵3',
  `get_fairy` int(10) unsigned NOT NULL COMMENT '获得的精灵',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `type_007_10002` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `accountid` int(10) NOT NULL,
  `userid` int(10) NOT NULL,
  `serverid` int(10) NOT NULL,
  `channel` int(10) NOT NULL,
  `typeid` int(10) NOT NULL,
  `appid` int(10) NOT NULL,
  `created_at` int(10) NOT NULL,
  `vip_level` int(10) NOT NULL,
  `client_time` int(10) NOT NULL,
  `shop_type` tinyint(2) NOT NULL COMMENT '商店类型，1：道具商店，2：联盟商店，3：冠军商店，4：环球商店，5：神秘商店，6：友好商店',
  `shop_name` varchar(32) NOT NULL COMMENT '商店名称',
  `buy_item_type` tinyint(2) NOT NULL COMMENT '商品类型，0：物品，6：精灵，18：努力点',
  `buy_item_id` int(10) unsigned NOT NULL COMMENT '购买的商品id',
  `buy_item_num` int(10) NOT NULL COMMENT '购买商品数量',
  `buy_item_name` varchar(32) NOT NULL COMMENT '购买的商品名称',
  `currency_type` tinyint(2) NOT NULL COMMENT '消耗的货币类型,1：金币，2：钻石，3：联盟币，4：冠军币，5：全球币，6：神秘积分，7：努力点，8：精力，9：体力',
  `currency_num` int(10) NOT NULL COMMENT '消耗货币数量',
  `currency_name` varchar(32) NOT NULL COMMENT '消耗的货币名称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;