DELETE FROM pre_activities_log;
DELETE FROM pre_activities_share;
DELETE FROM pre_apply_log;
DELETE FROM pre_car_log;
DELETE FROM pre_cash_log;
DELETE FROM pre_consume_log;
DELETE FROM pre_family;
DELETE FROM pre_family_log;
DELETE FROM pre_gift_log;
DELETE FROM pre_grab_log;
DELETE FROM pre_grabseat_log;
DELETE FROM pre_guard_list;
DELETE FROM pre_guard_log;
DELETE FROM pre_notice_configs;
DELETE FROM pre_online_gift;
DELETE FROM pre_order;
DELETE FROM pre_rank_log;
DELETE FROM pre_room_log;
DELETE FROM pre_room_user_status;
DELETE FROM pre_rooms;
DELETE FROM pre_sign_anchor;
DELETE FROM pre_task_log;
DELETE FROM pre_user_info;
DELETE FROM pre_user_log;
DELETE FROM pre_user_photo;
DELETE FROM pre_user_profiles;
DELETE FROM pre_users;

-- to 20150406